### ISSUE TITLE
rna_prob_transformer.yml Nan during training

### ISSUE THREAD

**Issue by JohnMcSpedon** [automl/ProbTransformer#2]
I've tried training with rna_prob_transformer.yml twice on a fresh clone of this codebase.  I'm running on GCP.  I'm using an `n1-highmem-4` instance with an NVIDIA V100 GPU.  The output log is included below.  In both runs, it's errored out on epoch 7

<details>
<summary>log_output.txt</summary>

```
2022-11-19_06:38:37.90 session_name: rna-experiments
2022-11-19_06:38:37.90 experiment_name: prob_transformer-0
2022-11-19_06:38:37.90 #################### CONFIG:
2022-11-19_06:38:37.90 sub config expt    : ['experiment_dir : experiment/rna-experiments/prob_transformer-0  ', 'experiment_name : prob_transformer-0  ', 'experiments_dir : experiment  ', 'save_model : True  ']
2022-11-19_06:38:37.90 sub config data    : ['batch_size : 4000  ', "rna : {'df_path': 'data/rna_data.plk', 'df_set_name': 'train', 'max_length': 500, 'min_length': 20, 'similarity': 80}  ", 'seed : 5874  ', "sub_config : ['rna']  ", 'type : rna  ']
2022-11-19_06:38:37.90 sub config rna     : ['df_path : data/rna_data.plk  ', 'df_set_name : train  ', 'max_length : 500  ', 'min_length : 20  ', 'similarity : 80  ']
2022-11-19_06:38:37.90 sub config geco_criterion: ['kappa : 0.1  ', 'kappa_adaption : True  ', 'lagmul_rate : 0.1  ', 'ma_decay : 0.95  ']
2022-11-19_06:38:37.90 sub config model   : ['dropout : 0.1  ', 'ff_factor : 4  ', 'max_len : 500  ', 'model_dim : 512  ', 'model_type : prob_encoder  ', 'n_layers : 6  ', 'num_head : 8  ', 'prob_layer : middle  ', 'z_factor : 1.0  ', 'zero_init : True  ']
2022-11-19_06:38:37.90 sub config optim   : ['beta1 : 0.9  ', 'beta2 : 0.98  ', 'clip_grad : 100  ', 'lr_high : 0.0005  ', 'lr_low : 5e-05  ', 'optimizer : adamW  ', 'scheduler : cosine  ', 'warmup_epochs : 1  ', 'weight_decay : 0.01  ']
2022-11-19_06:38:37.91 sub config train   : ['amp : False  ', 'epochs : 100  ', 'eval_freq : 10  ', 'grad_scale : 65536.0  ', 'iter_per_epoch : 10000  ', 'n_sampling : 10  ', 'save_freq : 10  ', 'seed : 5874  ']
2022-11-19_06:38:37.91 rank 0 ### START TRAINING ### at john-probtransformer
2022-11-19_06:38:37.91 ### load data
2022-11-19_06:39:01.76 ### load iterator
2022-11-19_06:39:01.76 train_set_size: 60,372
2022-11-19_06:39:01.76 valid_set_size: 1,299
2022-11-19_06:39:01.76 test_set_size: 1,350
2022-11-19_06:39:01.76 src_vocab_len: 5
2022-11-19_06:39:01.76 tgt_vocab_len: 13
2022-11-19_06:39:02.31 model_parameters: 46,237,197
2022-11-19_06:39:08.41 rank 0 start GPU training
2022-11-19_06:39:08.41 trainable_parameters: 46,237,198
2022-11-19_06:39:08.41 #0## START epoch 0 ####################################
2022-11-19_06:39:08.42 ## Start validation
2022-11-19_06:39:16.45 valid_mean_batch_size: 13.391752577319588  step:0
2022-11-19_06:39:16.45 valid_step: 96  step:0
2022-11-19_06:39:16.45 valid_mean_seq_len: 297.2680412371134  step:0
2022-11-19_06:39:16.45 valid_loss: 2.972703456878662  step:0
2022-11-19_06:39:16.45 timer valid: 0:00:08.030923  step:0
2022-11-19_06:39:16.45 ## Start valid evaluation
2022-11-19_06:50:20.27 hamming_distance_valid: 121.29176289453426  step:0
2022-11-19_06:50:20.27 word_error_rate_valid: 0.9238803528446857  step:0
2022-11-19_06:50:20.27 mat_solved_valid: 0.0  step:0
2022-11-19_06:50:20.27 seq_solved_valid: 0.0  step:0
2022-11-19_06:50:20.27 mat_all_f1_score_valid: 0.00869972288432642  step:0
2022-11-19_06:50:20.27 mat_all_solved_valid: 0.0  step:0
2022-11-19_06:50:20.27 mat_wc_f1_score_valid: 0.026979992163695402  step:0
2022-11-19_06:50:20.27 mat_wc_solved_valid: 0.0  step:0
2022-11-19_06:50:20.27 mat_canonical_f1_score_valid: 0.020410290692538774  step:0
2022-11-19_06:50:20.27 mat_canonical_solved_valid: 0.0  step:0
2022-11-19_06:50:20.27 mat_wobble_f1_score_valid: 0.006997586971314592  step:0
2022-11-19_06:50:20.27 mat_wobble_solved_valid: 0.0  step:0
2022-11-19_06:50:20.28 mat_nc_f1_score_valid: 0.0013605951207224386  step:0
2022-11-19_06:50:20.28 mat_nc_solved_valid: 0.0  step:0
2022-11-19_06:50:20.28 seq_all_f1_score_valid: 0.00869972288432642  step:0
2022-11-19_06:50:20.28 seq_all_solved_valid: 0.0  step:0
2022-11-19_06:50:20.28 seq_wc_f1_score_valid: 0.026979992163695402  step:0
2022-11-19_06:50:20.28 seq_wc_solved_valid: 0.0  step:0
2022-11-19_06:50:20.28 seq_canonical_f1_score_valid: 0.020410290692538774  step:0
2022-11-19_06:50:20.28 seq_canonical_solved_valid: 0.0  step:0
2022-11-19_06:50:20.28 seq_wobble_f1_score_valid: 0.006997586971314592  step:0
2022-11-19_06:50:20.28 seq_wobble_solved_valid: 0.0  step:0
2022-11-19_06:50:20.28 seq_nc_f1_score_valid: 0.0013605951207224386  step:0
2022-11-19_06:50:20.28 seq_nc_solved_valid: 0.0  step:0
2022-11-19_06:50:20.28 threshold_valid: 0.0  step:0
2022-11-19_06:50:20.28 samples_valid: 1,299  step:0
2022-11-19_06:50:20.28 PDB_samples_valid: 0  step:0
2022-11-19_06:50:20.28 timer eval: 0:11:03.829936  step:0
2022-11-19_06:50:20.28 LOGGER: save log to json
2022-11-19_06:50:20.28 timer epoch: 0:11:11.863737  step:0
2022-11-19_06:50:20.28 #0## START epoch 1 ####################################
2022-11-19_06:50:20.28 ## Start training
2022-11-19_07:19:23.03 train_mean_batch_size: 11.295670432956705  step:1
2022-11-19_07:19:23.03 train_step: 10000  step:1
2022-11-19_07:19:23.03 train_mean_seq_len: 276.84581541845813  step:1
2022-11-19_07:19:23.03 train_loss: 1909277.375  step:1
2022-11-19_07:19:23.03 train_ma_ce_loss: 0.3979755938053131  step:1
2022-11-19_07:19:23.03 train_rec_constraint: 0.2979755699634552  step:1
2022-11-19_07:19:23.03 train_lamb: 1.6993319988250732  step:1
2022-11-19_07:19:23.03 timer train: 0:29:02.750299  step:1
2022-11-19_07:19:23.03 ## Start validation
2022-11-19_07:19:29.77 valid_mean_batch_size: 13.391752577319588  step:1
2022-11-19_07:19:29.77 valid_step: 96  step:1
2022-11-19_07:19:29.77 valid_mean_seq_len: 297.2680412371134  step:1
2022-11-19_07:19:29.77 valid_loss: 5.316746234893799  step:1
2022-11-19_07:19:29.77 timer valid: 0:00:06.743515  step:1
2022-11-19_07:19:29.77 LOGGER: save log to json
2022-11-19_07:19:29.77 timer epoch: 0:29:09.497282  step:1
2022-11-19_07:19:29.77 #0## START epoch 2 ####################################
2022-11-19_07:19:29.78 ## Start training
2022-11-19_07:48:23.57 train_mean_batch_size: 11.281971802819719  step:2
2022-11-19_07:48:23.57 train_step: 10000  step:2
2022-11-19_07:48:23.57 train_mean_seq_len: 276.5921407859214  step:2
2022-11-19_07:48:23.57 train_loss: 0.4796809256076813  step:2
2022-11-19_07:48:23.57 train_ma_ce_loss: 0.10007310658693314  step:2
2022-11-19_07:48:23.57 train_rec_constraint: 7.310703949769959e-05  step:2
2022-11-19_07:48:23.57 train_lamb: 1.722368597984314  step:2
2022-11-19_07:48:23.60 timer train: 0:28:53.823897  step:2
2022-11-19_07:48:23.60 ## Start validation
2022-11-19_07:48:30.40 valid_mean_batch_size: 13.391752577319588  step:2
2022-11-19_07:48:30.40 valid_step: 96  step:2
2022-11-19_07:48:30.40 valid_mean_seq_len: 297.2680412371134  step:2
2022-11-19_07:48:30.40 valid_loss: 4.588891506195068  step:2
2022-11-19_07:48:30.40 timer valid: 0:00:06.798150  step:2
2022-11-19_07:48:30.41 LOGGER: save log to json
2022-11-19_07:48:30.41 timer epoch: 0:29:00.633500  step:2
2022-11-19_07:48:30.41 #0## START epoch 3 ####################################
2022-11-19_07:48:30.41 ## Start training
2022-11-19_08:17:23.85 train_mean_batch_size: 11.26977302269773  step:3
2022-11-19_08:17:23.85 train_step: 10000  step:3
2022-11-19_08:17:23.85 train_mean_seq_len: 276.0884911508849  step:3
2022-11-19_08:17:23.85 train_loss: 122797.140625  step:3
2022-11-19_08:17:23.85 train_ma_ce_loss: 0.09983273595571518  step:3
2022-11-19_08:17:23.85 train_rec_constraint: -0.00016726639296393842  step:3
2022-11-19_08:17:23.85 train_lamb: 1.4553507566452026  step:3
2022-11-19_08:17:23.89 timer train: 0:28:53.483858  step:3
2022-11-19_08:17:23.89 ## Start validation
2022-11-19_08:17:30.60 valid_mean_batch_size: 13.391752577319588  step:3
2022-11-19_08:17:30.60 valid_step: 96  step:3
2022-11-19_08:17:30.60 valid_mean_seq_len: 297.2680412371134  step:3
2022-11-19_08:17:30.60 valid_loss: 3.2161824703216553  step:3
2022-11-19_08:17:30.60 timer valid: 0:00:06.711369  step:3
2022-11-19_08:17:30.62 LOGGER: save log to json
2022-11-19_08:17:30.62 timer epoch: 0:29:00.207094  step:3
2022-11-19_08:17:30.62 #0## START epoch 4 ####################################
2022-11-19_08:17:30.62 ## Start training
2022-11-19_08:46:18.81 train_mean_batch_size: 11.218878112188781  step:4
2022-11-19_08:46:18.81 train_step: 10000  step:4
2022-11-19_08:46:18.81 train_mean_seq_len: 277.05569443055697  step:4
2022-11-19_08:46:18.81 train_loss: 0.31542348861694336  step:4
2022-11-19_08:46:18.81 train_ma_ce_loss: 0.10002462565898895  step:4
2022-11-19_08:46:18.81 train_rec_constraint: 2.4622293494758196e-05  step:4
2022-11-19_08:46:18.81 train_lamb: 1.3204193115234375  step:4
2022-11-19_08:46:18.86 timer train: 0:28:48.243640  step:4
2022-11-19_08:46:18.86 ## Start validation
2022-11-19_08:46:25.60 valid_mean_batch_size: 13.391752577319588  step:4
2022-11-19_08:46:25.60 valid_step: 96  step:4
2022-11-19_08:46:25.60 valid_mean_seq_len: 297.2680412371134  step:4
2022-11-19_08:46:25.60 valid_loss: 3.3740925788879395  step:4
2022-11-19_08:46:25.60 timer valid: 0:00:06.742111  step:4
2022-11-19_08:46:25.62 LOGGER: save log to json
2022-11-19_08:46:25.62 timer epoch: 0:28:55.006809  step:4
2022-11-19_08:46:25.62 #0## START epoch 5 ####################################
2022-11-19_08:46:25.62 ## Start training
2022-11-19_09:15:20.22 train_mean_batch_size: 11.258074192580741  step:5
2022-11-19_09:15:20.22 train_step: 10000  step:5
2022-11-19_09:15:20.22 train_mean_seq_len: 277.64583541645834  step:5
2022-11-19_09:15:20.22 train_loss: 0.2748402953147888  step:5
2022-11-19_09:15:20.22 train_ma_ce_loss: 0.09999215602874756  step:5
2022-11-19_09:15:20.22 train_rec_constraint: -7.84039730206132e-06  step:5
2022-11-19_09:15:20.22 train_lamb: 1.246871829032898  step:5
2022-11-19_09:15:20.28 timer train: 0:28:54.658893  step:5
2022-11-19_09:15:20.28 ## Start validation
2022-11-19_09:15:27.02 valid_mean_batch_size: 13.391752577319588  step:5
2022-11-19_09:15:27.02 valid_step: 96  step:5
2022-11-19_09:15:27.02 valid_mean_seq_len: 297.2680412371134  step:5
2022-11-19_09:15:27.02 valid_loss: 2.44031023979187  step:5
2022-11-19_09:15:27.02 timer valid: 0:00:06.739088  step:5
2022-11-19_09:15:27.04 LOGGER: save log to json
2022-11-19_09:15:27.04 timer epoch: 0:29:01.416232  step:5
2022-11-19_09:15:27.04 #0## START epoch 6 ####################################
2022-11-19_09:15:27.04 ## Start training
2022-11-19_09:44:29.08 train_mean_batch_size: 11.302969703029698  step:6
2022-11-19_09:44:29.08 train_step: 10000  step:6
2022-11-19_09:44:29.09 train_mean_seq_len: 278.4669533046695  step:6
2022-11-19_09:44:29.09 train_loss: 0.27079758048057556  step:6
2022-11-19_09:44:29.09 train_ma_ce_loss: 0.09985461086034775  step:6
2022-11-19_09:44:29.09 train_rec_constraint: -0.0001453882723581046  step:6
2022-11-19_09:44:29.09 train_lamb: 1.1856918334960938  step:6
2022-11-19_09:44:29.16 timer train: 0:29:02.123255  step:6
2022-11-19_09:44:29.16 ## Start validation
2022-11-19_09:44:35.94 valid_mean_batch_size: 13.391752577319588  step:6
2022-11-19_09:44:35.94 valid_step: 96  step:6
2022-11-19_09:44:35.94 valid_mean_seq_len: 297.2680412371134  step:6
2022-11-19_09:44:35.94 valid_loss: 2.5517024993896484  step:6
2022-11-19_09:44:35.94 timer valid: 0:00:06.775530  step:6
2022-11-19_09:44:35.96 LOGGER: save log to json
2022-11-19_09:44:35.96 timer epoch: 0:29:08.924166  step:6
2022-11-19_09:44:35.96 #0## START epoch 7 ####################################
2022-11-19_09:44:35.96 ## Start training
Traceback (most recent call last):
  File "prob_transformer/train_transformer.py", line 353, in <module>
    train_prob_transformer(config=config)
  File "prob_transformer/train_transformer.py", line 173, in train_prob_transformer
    stats, summary = run_epoch(rank, cfg, train_iter, model, geco_criterion=geco_criterion, opti=optima)
  File "/home/john/ProbTransformer/prob_transformer/routine/training.py", line 52, in run_epoch
    infer_mean=False)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/john/ProbTransformer/prob_transformer/model/probtransformer.py", line 211, in forward
    _, p_z_list, _ = self.post_encoder(post_encoder_embed, src_mask[:, None, :])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/john/ProbTransformer/prob_transformer/module/probformer_stack.py", line 43, in forward
    src_act_new, z = layer(src_act, src_mask, enc_act, enc_mask, infer_mean=infer_mean)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/john/ProbTransformer/prob_transformer/module/probformer_block.py", line 43, in forward
    act_z, z = self.prob_layer(src_act, p_z, infer_mean)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/john/ProbTransformer/prob_transformer/module/probabilistic_forward.py", line 59, in forward
    z = torch.distributions.Normal(z_mean, z_std)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributions/normal.py", line 50, in __init__
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributions/distribution.py", line 56, in __init__
    f"Expected parameter {param} "
ValueError: Expected parameter loc (Tensor of shape (8, 486, 512)) of distribution Normal(loc: torch.Size([8, 486, 512]), scale: torch.Size([8, 486, 512])) to satisfy the constraint Real(), but found invalid values:
tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        ...,

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]]], device='cuda:0',
       grad_fn=<AddBackward0>)
```
</details>

To proceed, I'll try:
- [x] 1. reducing the learning rate
- [ ] 2. changing `seed` in the config data

**Comment by JoergFranke** [comment]
I had the same issues. Reducing the lr is the best option, but you can also reduce the grad clipping.

**Comment by JohnMcSpedon** [comment]
Thanks for the update!
